### ISSUE TITLE
cordyceps: `List` doesn't impl `Drop`

### ISSUE THREAD

**Issue by jamesmunns** [hawkw/mycelium#165]
As noticed while troubleshooting CI issues in https://github.com/hawkw/mycelium/pull/163, `cordyceps::List` does not implement Drop, meaning any items contained in that list at the time of the List falling out of scope will be permanently lost.

Additionally, the `Entry` type used for tests (including loom and miri tests) also does not implement drop, meaning that even if the LIST drops all of it's contained items, the individual items will likely be leaked.

Warning to Eliza: James may not actually understand how the List or List tests work, and the fact you store all the entries in a vec:

```rust
let entries: Vec<_> = (0..ops.len()).map(|i| entry(i as i32)).collect();
```
means that they all get dropped, and it doesn't matter that List doesn't impl drop.

Have a think about this after some coffee, and potentially close this issue if everything is working as expected.

**Comment by hawkw** [comment]
as we discussed on discord, it's the element *owning* the entry that's responsible for dropping it, rather than the list.
