### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by bjorn3** [hawkw/mycelium#169]
What license is this project under? I see the cordyceps crate declares MIT as license in it's Cargo.toml, but no other part seems to define a license.

**Comment by hawkw** [comment]
This is a personal hobby project that doesn't currently do anything of value, so I haven't really put any thought into licensing for public use yet. However, I have been considering publishing some parts of this code on Crates.io (such as the `cordyceps` crate), under MIT. I'm happy to license everything under the MIT license if people are interested in using other parts of this repository.

**Comment by hawkw** [comment]
PR #170 licenses everything under MIT.

I'd be excited to hear about any use of this code in other projects, so if you're interested in sharing what you're interested in using and why, I'd love to hear about it!

**Comment by bjorn3** [comment]
On the Bevy discord there was some discussion today about potentially wanting to use your bitfield macro. (It's a neat macro by the way!) The discussion was however kind of cut short after observing that most of mycelium doesn't have a license. I have just posted that you licensed it as MIT as reply to this discussion.

**Comment by hawkw** [comment]
Folks on the Bevy discord may also be interested to know that PR #171 factors out the bit manipulation module into its own crate, so it can now be used without depending on a bunch of other stuff that may not be needed. 

I'd like to release this crate on crates.io once I've done a bit more API cleanup and documentation.

**Comment by hawkw** [comment]
@bjorn3 as an update, I just released the bitfield crate: https://crates.io/crates/mycelium-bitfield
