### ISSUE TITLE
IOAPIC driver

### ISSUE THREAD

**Issue by hawkw** [hawkw/mycelium#28]
it's cooler than regular PIC

**Comment by hawkw** [comment]
if memory serves there is some kinda cursed bios data thing you need to use to like find out where the APIC lives, or something

**Comment by IsaacWoods** [comment]
The best way to find the address is to parse the ACPI tables, for which I have a [handy (imo) crate](https://github.com/rust-osdev/acpi)!

**Comment by hawkw** [comment]
oh, hey, #351 implemented this!
