### ISSUE TITLE
milestone: run a "hello world" wasm

### ISSUE THREAD

**Issue by hawkw** [hawkw/mycelium#40]
- we should be able to run a wasm that basically invokes `__wasi_fd_write` to stdout with the string "hello world".
- i don't care about anything else working
- it's okay if the wasm is interpreted
- we can just include it in the kernel image for now (rather than figuring out "fs")

**Comment by hawkw** [comment]
cc @iximeow

**Comment by mystor** [comment]
Resolved by #58
