### ISSUE TITLE
`cordyceps::List` docs for `push_*`/`pop_*` should claim constant time

### ISSUE THREAD

**Issue by dataphract** [hawkw/mycelium#429]
The docs for `push_front()`, `push_back()`, `pop_front()` and `pop_back()` all have the following:

> This operation should compute in *O*(*n*) time.

As best I can tell from reading the source, these are all constant-time operations -- the methods traverse at most two nodes.

**Comment by hawkw** [comment]
Whoops, I think this was a copy-paste mishap --- good catch!
