### ISSUE TITLE
have an actual HAL-exposed oops handler

### ISSUE THREAD

**Issue by iximeow** [hawkw/mycelium#49]
our tentative [x86_64 double fault handler](https://github.com/hawkw/mycelium/pull/48/files#diff-a4d7ebc529bc18ebeb4d22d0229d5d4dR82-R91) prints some cpu state and hangs, but we'll probably want a higher level kernel panic to dump kernel state _and also_ architecture-specific state

**Comment by hawkw** [comment]
yeah this would be good

**Comment by hawkw** [comment]
if we panic in the hal, we'll hit this: https://github.com/hawkw/mycelium/blob/dd981a3efeb9f803e6671e93977e9bf30bf8e9c5/src/lib.rs#L61-L68

maybe we want to hang more debug info off of that?
