### ISSUE TITLE
consider running `cargo xclippy` in CI

### ISSUE THREAD

**Issue by mystor** [hawkw/mycelium#67]
Currently we run `cargo clippy` on the host platform, meaning that code which is only built for the target OS won't be linted against. It may be worthwhile to run `cargo xclippy` instead/in addition during CI to improve linting coverage.

This will unfortunately be substantially slower than `cargo clippy`, as it will require installing `cargo-xbuild`, and building the custom target's toolchain, but it may be worthwhile.

**Comment by hawkw** [comment]
It looks like [we are doing this now](https://github.com/hawkw/mycelium/blob/46ec0f6b788f6f5cd522a2e609210c296e18c16a/.github/workflows/rust.yml#L94-L120)?

**Comment by mystor** [comment]
Oh, I suppose we are! It's not hooked into cargo-clippy, but we should be running it now.
