### ISSUE TITLE
page frame allocation

### ISSUE THREAD

**Issue by hawkw** [hawkw/mycelium#75]
now that we can map pages (#71) we need a page frame allocator before we can do anything interesting

**Comment by hawkw** [comment]
@mystor iirc, at one point, you said that there were certain VM sizes that we will have to allocate a lot of for wasm reasons, right? 

if so, we will probably want to tune the free list sharding based on that, so that there's a free list for chunks of each size that we have to allocate a lot of (+ free lists for small chunks that can be coalesced or fed to kernel heap allocators.

this also implies that _eventually_, the page frame allocator impl that mycelium uses should live in the kernel rather than in HAL (though there can be concrete allocator impls in HAL as well, esp. if they're _composed_ to form the kernel allocator). if we tune free list sizes to support wasm alloc patterns, that's _definitely_ mycelium-specific kernel policy...

**Comment by mystor** [comment]
Yes! wasm allocates heaps in 64k pages, so all allocation sizes are defined in terms of # of 64k pages.
We'll probably also want to make sure that wasm allocations are 4gig aligned in virtual memory, so that we don't need to bounds-check memory accesses from wasm, and can just add the 32-bit wasm address to our base address.

**Comment by hawkw** [comment]
I guess the cap is probably that a wasm will never allocate more than 4gb of 64k pages?

**Comment by mystor** [comment]
Each wasm32 can encode their maximum memory size in metadata, so the limit may be lower than 4gb, but the maximum would be 4gb of 64k pages, as any more wouldn't be addressable with a u32. (more could be allowed with wasm64)

Using 4gb of virtual address space reserved, but not mapped, just allows us to avoid bounds-checking memory accesses within wasm.

**Comment by hawkw** [comment]
oh, i got this working on x86 (preliminary) in #86!
